### ISSUE TITLE
입력 테스트 후 수정 요청

### ISSUE THREAD

**Issue by yskwonwm** [WAVEM-Inc/visualization#1]
branch : KEC/Linux/JaeHyeok/Feature/route_editor/NodeEditor
commit : 7835893087cfc6939eb86b26b6986b4368d0f175

1.파일의 경위도 자리수 소수점 7자리 되어야함
2.파일의 kind는 코드로 파일에 저장되어야 함(intersection,connecting,endpoint,wating)
3.파일의 direction은 전방,후방 코드(forward,backward)로 저장되어야함
4.우측 패널 완료 버튼 -> 저장,닫기 로 구분 할것
5.우측 패널이 있는 경우 노드 입력 팝업이 가려서 안보임
6.좌측 하단 경로 리스트는 세로로 길게
7.작업 구분의 기본 값은 '연결'- 현재는 마지막 선택 값으로 되어 있음\
8.하단 경로 목록에서 노드 드래그로 중간 삽입 안됨(
9.위치 저장에서 '지도위치로 저장','차량위치로 저장'버튼을 클릭하면 각 지도위치 or GPS위치가 표시되는 건가?
10.감지 범위 입력시 위도/경도 는 GPS 수신 정보가 표출되어야함
11.감지 범위 입력시 상단에 0은 뭐지?
12.감지 범위 입력시 입력 창 순서는 위도/경로 순으로 통일할것

**Comment by yskwonwm** [comment]
수정사항

1. 노드 진출 각 정북인 경우 360 -> 0
2. 감지 범위 노드 오타(둘다 감지폭(좌))
3. 감지 범위 영역은 노드 진행 방향과 맞지 않음(대기경로의 9012노드의 영역, 호출 1004 영역)
4. 영역 각도가 안맞음 대상노드 진출가기 0 인데 영역이 기울어져 있음(대기 경로 3002노드)
**첨부 파일 참조**
[KEC_ROUTE_20240325.txt](https://github.com/WAVEM-Inc/visualization/files/14738080/KEC_ROUTE_20240325.txt)

**Comment by NTques** [comment]
현재까지 업로드 된 이슈 및 추가/개선 항목에 대한 코드 수정이 완료되었습니다.
확인 후 Close 부탁드립니다.
