### ISSUE TITLE
기능 추가  및 수정 요청 

### ISSUE THREAD

**Issue by yskwonwm** [WAVEM-Inc/visualization#6]
추가 및 수정 요청
 - 생성할 수 있는경로 최대 갯수  증가
 - 노드 진출 각도 계산 시점 추가(경위도버튼 클릭시에서 다음 노드와의 각도 계산하여 표시)
 - 선택한 노드의 시점 이동 시 우측 패널을 고려한 화면의 가운데로 이동해야함(현재는 전체 화면 기준)
 - 이미지맵 최대 확대 후에는 위치가 이상함(화면의 가운데로 이동하지 않음)
 - 버튼 가시성 확보 필요,야외에서는 화면이 보이지 않음(세로 사이즈 현재 2배,색상 넣을것)
 - 마우스 크기 확대(야외에서는 화면이 보이지 않음)

**Comment by yskwonwm** [comment]
수정 요청
- 감지범위 -> 감지후 처리코드 의 명칭 및 값 변경
    : 무시(skip)->협동주행(cooperative)

**Comment by yskwonwm** [comment]
1. 노드 ID가 잘림
<img src="https://github.com/WAVEM-Inc/visualization/assets/87844157/d131d7b1-5bd1-4191-a23f-629e98459a4f" width="200" height="300">

2. 변경된 마우스 포인트의 지점이 좌측 상단이 아니고 이미지의 가운데로 되어 있음
   - 좌측 상단 뾰족한 부분으로 변경 혹은 디폴트 마우스 포인트로 원복

3. 촤측 패널의 경로id리스트 정렬 변경 요청
    - 경로id -> 경로명 으로 정렬을 변경 (경로 id는 사용자에게 무의미한 정보임)

4. 차량 방향이 0도 인경우가 있고 360인 경우가 있음. 차이가 무엇인가?
<img src="https://github.com/WAVEM-Inc/visualization/assets/87844157/1d8f46f5-e443-4088-ade8-edad8da8dc81" width="200" height="300">
<img src="https://github.com/WAVEM-Inc/visualization/assets/87844157/f4f2be0b-7dcd-4157-9c85-a1c540e69b28" width="200" height="300">

**Comment by yskwonwm** [comment]
작업 계획 코멘트 바랍니다.

**Comment by yskwonwm** [comment]
![image](https://github.com/WAVEM-Inc/visualization/assets/87844157/b914b0c9-8223-4678-948b-4b19162895dc)

1. node id 필드에 node_name이 들어감
json 파일에서 nodeName 항목이 아닌 nodeId항목을 보여줘야함

2. 경로 정렬을 코드명이 아닌 경로명으로  해야함

**Comment by yskwonwm** [comment]
작업 계획 코멘트 바랍니다.

**Comment by yskwonwm** [comment]
노드 정보 추가 요청

1. 화면 우측 노드 정보 패널에 입력 필드 추가 
    속도 , 도착옵션

2. Node 정보 추가
         "speed"           -    차량 속도(float) 
         "arriveOption"  -   "Drive","Stop"   :  default 는 "Stop"

3. 예시
 {
                    "detectionRange": [],
                    "direction": "forward",
                    "drivingOption": "odom",
                    "heading": 236,
                    "kind": "endpoint",
                    "nodeId": "NO-966-1001",
                    "position": {
                        "latitude": 36.1138036,
                        "longitude": 128.3674185
                    },
                    "type": "work_node"
                    "speed": 1.2
                    "arriveOption":  "Drive"
                },

**Comment by NTques** [comment]
아래 항목은 완료되었습니다.

노드 정보 추가 요청

화면 우측 노드 정보 패널에 입력 필드 추가
속도 , 도착옵션

Node 정보 추가
"speed" - 차량 속도(float)
"arriveOption" - "Drive","Stop" : default 는 "Stop"

예시
{
"detectionRange": [],
"direction": "forward",
"drivingOption": "odom",
"heading": 236,
"kind": "endpoint",
"nodeId": "NO-966-1001",
"position": {
"latitude": 36.1138036,
"longitude": 128.3674185
},
"type": "work_node"
"speed": 1.2
"arriveOption": "Drive"
},

아래 항목은 주중까지 업데이트 하겠습니다.

node id 필드에 node_name이 들어감
json 파일에서 nodeName 항목이 아닌 nodeId항목을 보여줘야함

경로 정렬을 코드명이 아닌 경로명으로 해야함

**Comment by yskwonwm** [comment]
기존 맵 파일을 읽을수 있어야함. 기존 맵을 읽어서 speed,arriveOption 을 추가 할수 있어야 함.
즉, 기존 맵 파일을 열어서 경로에서  speed,arriveOption 을 추가 해서 저장하면 파일에 speed,arriveOption  키와 값이 추가 되어야함.

아니면 경로맵을 노드 추가 부터 모두 새로 만들어야 해서 현재 상황으로는 사용 불가능함

**Comment by yskwonwm** [comment]
> 아래 항목은 완료되었습니다.
> 
> 노드 정보 추가 요청
> 
> 화면 우측 노드 정보 패널에 입력 필드 추가 속도 , 도착옵션
> 
> Node 정보 추가 "speed" - 차량 속도(float) "arriveOption" - "Drive","Stop" : default 는 "Stop"
> 
> 예시 { "detectionRange": [], "direction": "forward", "drivingOption": "odom", "heading": 236, "kind": "endpoint", "nodeId": "NO-966-1001", "position": { "latitude": 36.1138036, "longitude": 128.3674185 }, "type": "work_node" "speed": 1.2 "arriveOption": "Drive" },
> 
> 아래 항목은 주중까지 업데이트 하겠습니다.
> 
> node id 필드에 node_name이 들어감 json 파일에서 nodeName 항목이 아닌 nodeId항목을 보여줘야함
> 
> 경로 정렬을 코드명이 아닌 경로명으로 해야함

맵 데이터에 arriveOption 및 speed 필드 추가 하는것은 일정상 취소되었음.
맵 데이터를 수정하지 않고 기존 값으로 처리 하는 것으로 변경 하였음.
따라서 arriveOption 및 speed 필드 추가 된 기능은 삭제 하고 아래 두개반 반영해 주기 바랍니다.

1. node id 필드에 node_name이 들어가지 않도록함
2. 경로 정렬을 코드명이 아닌 경로명으로 해야함

**Comment by NTques** [comment]
수정하여 업로드 하였습니다.
아래 링크 확인부탁드립니다
https://github.com/WAVEM-Inc/visualization/pull/15

**Comment by yskwonwm** [comment]
브랜치 KEC/Linux/Develop 를 받으면 되는 건가요?
이것으로 clone 해서 새로 받았는데 아래와 같은 에러가 나타납니다.

terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key 'speed' not found
중지됨 (코어 덤프됨)

**Comment by NTques** [comment]
> 브랜치 KEC/Linux/Develop 를 받으면 되는 건가요? 이것으로 clone 해서 새로 받았는데 아래와 같은 에러가 나타납니다.
> 
> terminate called after throwing an instance of 'nlohmann::detail::out_of_range' what(): [json.exception.out_of_range.403] key 'speed' not found 중지됨 (코어 덤프됨)

KEC/Linux/Develop 브랜치는 동일합니다.
이전 history 확인해보니 제대로 merge 된 것 같지 않아 다시 업데이트 하였습니다.

확인 부탁드립니다.
